#!/usr/bin/env bash
# title: Автоповтор русификации после «omarchy update»
# group: ui
# default: off
# desc: хук post-update.d: после обновления Omarchy заново собирает русское меню и копию Super+K-меню с новыми пунктами
set -euo pipefail
D="$HOME/.local/share/omarchy-rus"
HOOK_DIR="$HOME/.config/omarchy/hooks/post-update.d"
# Скрипты копируются в постоянное место: папка с распакованным архивом может быть удалена.
mkdir -p "$D" "$HOOK_DIR"
install -m 755 "$RUS_DIR/translate-menu.py" "$RUS_DIR/keybindings-ru.py" "$D/"
cat > "$HOOK_DIR/omarchy-rus.hook" <<'HOOK'
#!/bin/bash
# Установлен omarchy-rus (модуль post-update-hook). Обновление Omarchy могло добавить пункты меню и
# изменить стоковый omarchy-menu-keybindings: пересобираем только то, что уже было установлено.
D="$HOME/.local/share/omarchy-rus"
if grep -qF "Generated by omarchy-rus" "$HOME/.config/omarchy/extensions/omarchy-menu.jsonc" 2>/dev/null; then
  python3 "$D/translate-menu.py" || echo "omarchy-rus: не удалось обновить меню"
fi
if [ -x "$HOME/.local/bin/omarchy-menu-keybindings-ru" ]; then
  python3 "$D/keybindings-ru.py" wrapper || echo "omarchy-rus: не удалось обновить меню горячих клавиш"
fi
exit 0
HOOK
chmod +x "$HOOK_DIR/omarchy-rus.hook"
