#!/usr/bin/env python3
"""DNS-провайдеры для России в стоковом виджете сети Omarchy.

Стоковые пилюли DNS — Cloudflare и Google; `omarchy-dns` принимает только их (+ DHCP/Custom),
а менять его в /usr/share/omarchy/ нельзя. Поэтому две части:

  dns-ru.py helper OUT   генерирует из /usr/bin/omarchy-dns копию с российскими провайдерами.
                         Ставится ОТ root в /usr/local/bin/omarchy-dns-ru (делает модуль dns):
                         скрипт, который исполняется от root после polkit-диалога, не должен
                         быть доступен на запись пользователю.
  dns-ru.py panel        правит КЛОН виджета сети (~/.config/omarchy/plugins/<user>.network):
                         список провайдеров, пилюли, вызов omarchy-dns-ru и обновление
                         состояния после смены DNS (идея — WokoFlipper/omarchy-network-ru).

Список провайдеров — в PROVIDERS ниже, правится в одном месте. Идемпотентно.
"""
import getpass
import re
import sys
from pathlib import Path

STOCK = Path("/usr/bin/omarchy-dns")
HELPER_PATH = "/usr/local/bin/omarchy-dns-ru"
PANEL = Path.home() / ".config/omarchy/plugins" / f"{getpass.getuser()}.network" / "Panel.qml"

# Порядок = порядок пилюль после DHCP. Замерено отвечающими по IPv4 (UDP/53).
# tls — имя для DoT (systemd-resolved, режим opportunistic: сертификат не проверяется).
PROVIDERS = [
    {"name": "Yandex", "v4": ["77.88.8.8", "77.88.8.1"], "tls": "common.dot.dns.yandex.net",
     "detect": ["77.88.8.8", "77.88.8.1"], "tip": "DNS: Яндекс (77.88.8.8)"},
    {"name": "DNS4EU", "v4": ["86.54.11.100", "86.54.11.200"], "tls": "unfiltered.joindns4.eu",
     "detect": ["86.54.11.", "joindns4.eu"], "tip": "DNS: DNS4EU (86.54.11.100)"},
    {"name": "NextDNS", "v4": ["45.90.28.0", "45.90.30.0"], "tls": "dns.nextdns.io",
     "detect": ["45.90.28.", "45.90.30.", "nextdns.io"], "tip": "DNS: NextDNS (45.90.28.0)"},
]
FALLBACK = ("FallbackDNS=9.9.9.9#dns.quad9.net 149.112.112.112#dns.quad9.net "
            "2620:fe::fe#dns.quad9.net 2620:fe::9#dns.quad9.net")


def die(msg: str) -> "None":
    print(f"dns-ru: {msg}", file=sys.stderr)
    sys.exit(1)


def replace_once(text: str, old: str, new: str, what: str) -> str:
    if text.count(old) != 1:
        die(f"не найден якорь «{what}» в стоковом omarchy-dns (он изменился?) — helper не создан")
    return text.replace(old, new)


def build_helper() -> str:
    if not STOCK.exists():
        die(f"{STOCK} не найден")
    t = STOCK.read_text()

    t = replace_once(t, "PACKAGED_PATH=/usr/bin/omarchy-dns", f"PACKAGED_PATH={HELPER_PATH}", "PACKAGED_PATH")

    arg_arms = "".join(
        f'  {p["name"]} | {p["name"].lower()})\n    echo "{p["name"]}"\n    ;;\n' for p in PROVIDERS)
    t = replace_once(t, '  DHCP | dhcp)\n    echo "DHCP"', arg_arms + '  DHCP | dhcp)\n    echo "DHCP"', "provider_from_arg")

    detect = ""
    for p in PROVIDERS:
        cond = " || ".join(f'$dns == *"{d}"*' for d in p["detect"])
        detect += f'  elif [[ {cond} ]]; then\n    echo "{p["name"]}"\n'
    t = replace_once(t, '  else\n    echo "Custom"\n  fi', detect + '  else\n    echo "Custom"\n  fi', "current_dns_provider")

    case_arms = ""
    for p in PROVIDERS:
        csv = ",".join(p["v4"])
        spc = " ".join(p["v4"])
        dns_line = " ".join(f'{ip}#{p["tls"]}' for ip in p["v4"])
        case_arms += (
            f'{p["name"]})\n'
            f'  write_networkmanager_dns "{csv}"\n'
            f'  set_connection_dns "{spc}" ""\n'
            f"  tee /etc/systemd/resolved.conf >/dev/null <<'EOF'\n"
            f"[Resolve]\nDNS={dns_line}\n{FALLBACK}\nDNSOverTLS=opportunistic\nEOF\n  ;;\n\n")
    t = replace_once(t, "\nDHCP)\n  clear_networkmanager_dns", "\n" + case_arms + "DHCP)\n  clear_networkmanager_dns", "case DHCP")

    names = "|".join(["Cloudflare", "Google"] + [p["name"] for p in PROVIDERS] + ["DHCP", "Custom"])
    t = t.replace("omarchy-dns [Cloudflare|Google|DHCP|Custom]", f"omarchy-dns-ru [{names}]")
    header = ("# Generated by omarchy-rus/dns-ru.py from /usr/bin/omarchy-dns. Do not edit;\n"
              "# regenerate with modules/56-dns.sh after omarchy updates.\n")
    lines = t.split("\n", 1)
    return lines[0] + "\n" + header + lines[1]


def pill(name: str, index: int, tip: str) -> str:
    return (f'          DnsProviderPill {{\n'
            f'            provider: "{name}"\n'
            f'            index: {index}\n'
            f'            tooltipText: "{tip}"\n'
            f'            width: dnsRow.cellWidth\n'
            f'            onClicked: root.setDns(provider)\n'
            f'          }}\n')


def block_end(text: str, start: int) -> int:
    depth = 0
    for i in range(start, len(text)):
        if text[i] == "{":
            depth += 1
        elif text[i] == "}":
            depth -= 1
            if depth == 0:
                return i + 1
    die("не удалось найти конец блока Row")


def patch_panel() -> None:
    if not PANEL.exists():
        die(f"{PANEL} не найден: сначала склонируйте плагин (translate-plugins.py network)")
    t = PANEL.read_text()
    names = ["DHCP"] + [p["name"] for p in PROVIDERS] + ["Custom"]

    t, n = re.subn(r"readonly property var dnsProviders: \[[^\]]*\]",
                   "readonly property var dnsProviders: [" + ", ".join(f'"{x}"' for x in names) + "]", t)
    if n != 1:
        die("не найден dnsProviders в Panel.qml")

    t, n = re.subn(r'var command = "omarchy-dns(-ru)?"', 'var command = "omarchy-dns-ru"', t)
    if n != 1:
        die("не найден dnsCommand в Panel.qml")

    m = re.search(r"        Row \{\n          id: dnsRow\b", t)
    if not m:
        die("не найден Row с пилюлями DNS")
    start, end = m.start(), block_end(t, m.start() + len("        Row "))
    tips = {"DHCP": "Использовать DNS от DHCP", "Custom": "Задать свои DNS-серверы"}
    tips.update({p["name"]: p["tip"] for p in PROVIDERS})
    row = ("        Row {\n          id: dnsRow\n          width: parent.width\n          spacing: Style.space(6)\n\n"
           f"          readonly property int count: {len(names)}\n"
           "          readonly property real cellWidth: (width - spacing * (count - 1)) / count\n\n"
           + "\n".join(pill(n_, i, tips[n_]) for i, n_ in enumerate(names))
           + "        }")
    t = t[:start] + row + t[end:]

    marker = "// omarchy-rus: DNS switch reloads the NM stack"
    if marker not in t:
        old = '        root.pendingDnsProvider = ""\n'
        if t.count(old) != 1:
            die("не найден обработчик завершения смены DNS")
        t = t.replace(old, old + f"        {marker}; pull fresh state now\n        root.refresh()\n")

    PANEL.write_text(t)
    print(f"dns-ru: виджет сети обновлён ({', '.join(names)})")


def main() -> None:
    cmd = sys.argv[1] if len(sys.argv) > 1 else ""
    if cmd == "helper" and len(sys.argv) == 3:
        Path(sys.argv[2]).write_text(build_helper())
    elif cmd == "panel":
        patch_panel()
    else:
        print(__doc__)
        sys.exit(2)


if __name__ == "__main__":
    main()
