#!/usr/bin/env python3
"""Русификация меню Omarchy.

Читает стандартное меню (/usr/share/omarchy/default/omarchy/omarchy-menu.jsonc) и
генерирует пользовательское расширение ~/.config/omarchy/extensions/omarchy-menu.jsonc,
в котором переопределены пункты с переведёнными label/title. Пункты пишутся ЦЕЛИКОМ:
Omarchy при слиянии подставляет пустые значения для отсутствующих полей и затирает action/icon/when.
Новые пункты будущих версий Omarchy остаются на английском, пока их не добавят в словарь.
Файлы в /usr/share/omarchy/ не меняются.
"""
import json
import re
import shutil
import sys
import time
from pathlib import Path

DEFAULT = Path("/usr/share/omarchy/default/omarchy/omarchy-menu.jsonc")
TARGET = Path.home() / ".config/omarchy/extensions/omarchy-menu.jsonc"
MARKER = "// Generated by omarchy-rus/translate-menu.py"

# Подписи (label). Названия программ и брендов не переводятся.
LABELS = {
    # корень
    "Apps": "Приложения", "Learn": "Обучение", "Trigger": "Действия", "Style": "Стиль",
    "Setup": "Настройка", "Install": "Установка", "Remove": "Удаление", "Update": "Обновление",
    "About": "О системе", "System": "Система",
    # система
    "Screensaver": "Заставка", "Lock": "Блокировка", "Suspend": "Сон", "Hibernate": "Гибернация",
    "Logout": "Выход", "Reboot": "Перезагрузка", "Shutdown": "Выключение",
    # обучение
    "Keybindings": "Горячие клавиши", "Community": "Сообщество",
    # действия
    "Emoji": "Эмодзи", "Reminder": "Напоминание", "Capture": "Захват", "Screenshot": "Снимок экрана",
    "Stop Screenrecording": "Остановить запись экрана", "Screenrecord": "Запись экрана",
    "Text": "Текст", "QR Code": "QR-код", "Color": "Цвет",
    "With no audio": "Без звука", "With desktop audio": "Со звуком рабочего стола",
    "With desktop + microphone audio": "Со звуком рабочего стола и микрофона",
    "With desktop + microphone audio + webcam": "Со звуком рабочего стола, микрофона и веб-камерой",
    "Transcode": "Перекодирование", "Share": "Поделиться", "Toggle": "Переключатели",
    "Hardware": "Оборудование", "Speed Test": "Тест скорости",
    "Laptop Display": "Экран ноутбука", "Mirror Display": "Дублирование экрана",
    "Hybrid GPU": "Гибридная графика", "Touchpad": "Тачпад", "Touchpad Haptics": "Отклик тачпада",
    "low": "слабый", "mid": "средний", "high": "сильный", "Touchscreen": "Сенсорный экран",
    "Set one": "Создать", "Show all": "Показать все", "Clear all": "Удалить все",
    "Clipboard": "Буфер обмена", "File": "Файл", "Folder": "Папка", "Receive": "Получить",
    "Stay Awake": "Не засыпать", "Notifications": "Уведомления", "Crash Capture": "Перехват сбоев",
    "Nightlight": "Ночной свет", "Menu Bar": "Панель меню", "Battery Percentage": "Процент заряда",
    "Workspace Layout": "Раскладка рабочих столов", "Window Gaps": "Отступы окон",
    "1-Window Ratio": "Пропорции одного окна",
    "Network Speed Test": "Скорость сети", "Disk Speed Test": "Скорость диска",
    # стиль
    "Theme": "Тема", "Background": "Фон", "Unlock": "Разблокировка", "Font": "Шрифт",
    "Position": "Положение", "Transparency": "Прозрачность",
    "Top": "Сверху", "Bottom": "Снизу", "Left": "Слева", "Right": "Справа",
    "Edit Text": "Изменить текст", "Set From Image": "Задать из изображения",
    "Restore Default": "Вернуть по умолчанию",
    # настройка
    "Monitors": "Мониторы", "Input": "Ввод", "Network": "Сеть", "Custom": "Свой",
    "Defaults": "По умолчанию", "Agent": "Агент", "Browser": "Браузер", "Terminal": "Терминал",
    "Editor": "Редактор", "Plugins": "Плагины", "Enable Plugin": "Включить плагин",
    "Disable Plugin": "Отключить плагин", "Add Plugin": "Добавить плагин",
    "Clone Plugin": "Клонировать плагин", "Remove Plugin": "Удалить плагин",
    "Security": "Безопасность", "Config": "Конфигурация", "Fingerprint": "Отпечаток пальца",
    "Passwordless Sudo": "Sudo без пароля", "Sudoless Docker": "Docker без sudo",
    "Direct Boot": "Прямая загрузка", "Reset Computer": "Сброс компьютера",
    # установка / удаление
    "Package": "Пакет", "Web App": "Веб-приложение", "Service": "Сервис", "Services": "Сервисы",
    "Development": "Разработка", "AI": "ИИ", "Gaming": "Игры", "Windows": "Windows",
    "Preinstalls": "Предустановленное", "Dictation": "Диктовка", "Xbox Controllers": "Геймпады Xbox",
    "Chromium Account": "Аккаунт Chromium", "Docker DB": "БД в Docker",
    "Heroic (Epic Games)": "Heroic (Epic Games)", "RetroArch Game Launcher": "Лаунчер игр RetroArch",
    # обновление
    "Channel": "Канал", "Extra Themes": "Доп. темы", "Process": "Процесс", "Firmware": "Прошивка",
    "Password": "Пароль", "Timezone": "Часовой пояс", "Time": "Время", "Stable": "Стабильный",
    "Audio": "Звук", "Bluetooth": "Bluetooth", "Trackpad": "Трекпад",
    "Drive Encryption": "Шифрование диска", "User": "Пользователь",
}

# Заголовки подменю (title). Если title не задан — используется label.
TITLES = {
    "Default Agent": "Агент по умолчанию", "Default Browser": "Браузер по умолчанию",
    "Default Terminal": "Терминал по умолчанию", "Default Editor": "Редактор по умолчанию",
    "Remove": "Удаление", "Reset to default": "Сброс к умолчанию", "Restart": "Перезапуск",
}


def main() -> int:
    if not DEFAULT.exists():
        print(f"translate-menu: не найден {DEFAULT}", file=sys.stderr)
        return 1

    # Omarchy подставляет пустые значения для отсутствующих полей, поэтому
    # переопределять нужно пункт целиком (иначе теряются action/icon/when/provider).
    raw = DEFAULT.read_text()
    raw = re.sub(r"^\s*//[^\n]*(\n|$)", "", raw, flags=re.M)
    raw = re.sub(r",(\s*[}\]])", r"\1", raw)
    default = json.loads(raw)
    default = default.get("items", default)

    out = {}
    for key, entry in default.items():
        new = dict(entry)
        if entry.get("label") in LABELS:
            new["label"] = LABELS[entry["label"]]
        if entry.get("title") in TITLES:
            new["title"] = TITLES[entry["title"]]
        # Меню «Обучение → Горячие клавиши» открывает переведённую версию, если модуль keybindings её собрал.
        wrapper = Path.home() / ".local/bin/omarchy-menu-keybindings-ru"
        if key == "learn.keybindings" and wrapper.exists():
            new["action"] = str(wrapper)
        if new != entry:
            out[key] = new

    TARGET.parent.mkdir(parents=True, exist_ok=True)
    if TARGET.exists() and MARKER not in TARGET.read_text():
        backup = TARGET.with_suffix(f".jsonc.bak.{int(time.time())}")
        shutil.copy2(TARGET, backup)
        print(f"translate-menu: резервная копия {backup}")

    lines = [MARKER, "// Не редактируйте вручную: перезапустите скрипт.", "{"]
    items = list(out.items())
    for i, (key, entry) in enumerate(items):
        comma = "," if i < len(items) - 1 else ""
        lines.append(f"  {json.dumps(key)}: {json.dumps(entry, ensure_ascii=False)}{comma}")
    lines.append("}")
    TARGET.write_text("\n".join(lines) + "\n")
    print(f"translate-menu: переведено {len(out)} пунктов → {TARGET}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
